#!/usr/bin/env python

import sys
from PySide import QtGui
from cdatgui import MainWindow
from cdatgui.utils import icon


app = QtGui.QApplication(sys.argv)
QtGui.QApplication.setWindowIcon(icon("beta-uvcdat-icon.png"))

window = MainWindow()
window.show()

sys.exit(app.exec_())
